package com.v2soft.training.model;
// Generated Oct 9, 2019, 1:39:32 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Employeeinfo generated by hbm2java
 */
@Entity
@Table(name = "employeeinfo", catalog = "employee", uniqueConstraints = @UniqueConstraint(columnNames = "SSN"))
public class Employee implements java.io.Serializable {

	private String employeeId;
	private String firstName;
	private String lastName;
	private String middleName;
	private Date dateOfBirth;
	private String ssn;
	private String passportNumber;
	private Set<Login> logins = new HashSet<Login>(0);
	private Set<EmployeeAddress> employeeAddresses = new HashSet<EmployeeAddress>(0);

	public Employee() {
	}

	public Employee(String employeeId, String firstName, String lastName, Date dateOfBirth, String ssn,
			String passportNumber) {
		this.employeeId = employeeId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.dateOfBirth = dateOfBirth;
		this.ssn = ssn;
		this.passportNumber = passportNumber;
	}

	public Employee(String employeeId, String firstName, String lastName, String middleName, Date dateOfBirth,
			String ssn, String passportNumber, Set<Login> logins, Set<EmployeeAddress> employeeAddresses) {
		this.employeeId = employeeId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.dateOfBirth = dateOfBirth;
		this.ssn = ssn;
		this.passportNumber = passportNumber;
		this.logins = logins;
		this.employeeAddresses = employeeAddresses;
	}

	@Id

	@Column(name = "Employee_Id", unique = true, nullable = false, length = 12)
	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "First_Name", nullable = false, length = 20)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "Last_Name", nullable = false, length = 20)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Middle_Name", length = 20)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_Of_Birth", nullable = false, length = 10)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "SSN", unique = true, nullable = false, length = 20)
	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	@Column(name = "Passport_Number", nullable = false, length = 20)
	public String getPassportNumber() {
		return this.passportNumber;
	}

	public void setPassportNumber(String passportNumber) {
		this.passportNumber = passportNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeinfo")
	public Set<Login> getLogins() {
		return this.logins;
	}

	public void setLogins(Set<Login> logins) {
		this.logins = logins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeinfo")
	public Set<EmployeeAddress> getEmployeeAddresses() {
		return this.employeeAddresses;
	}

	public void setEmployeeAddresses(Set<EmployeeAddress> employeeAddresses) {
		this.employeeAddresses = employeeAddresses;
	}

}
