package com.v2soft.training.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * LoginSession generated by hbm2java
 */
@Entity
@Table(name = "login_session", catalog = "employee")
public class LoginSession implements java.io.Serializable {

	private LoginSessionId id;
	private Login login;

	public LoginSession() {
	}

	public LoginSession(LoginSessionId id, Login login) {
		this.id = id;
		this.login = login;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userName", column = @Column(name = "userName", nullable = false, length = 20)),
			@AttributeOverride(name = "loginStatus", column = @Column(name = "login_status", nullable = false)) })
	public LoginSessionId getId() {
		return this.id;
	}

	public void setId(LoginSessionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "userName", nullable = false, insertable = false, updatable = false)
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

}

