package com.v2soft.training.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LoginSessionId generated by hbm2java
 */
@Embeddable
public class LoginSessionId implements java.io.Serializable {

	private String userName;
	private int loginStatus;

	public LoginSessionId() {
	}

	public LoginSessionId(String userName, int loginStatus) {
		this.userName = userName;
		this.loginStatus = loginStatus;
	}

	@Column(name = "userName", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "login_status", nullable = false)
	public int getLoginStatus() {
		return this.loginStatus;
	}

	public void setLoginStatus(int loginStatus) {
		this.loginStatus = loginStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginSessionId))
			return false;
		LoginSessionId castOther = (LoginSessionId) other;

		return ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
				&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& (this.getLoginStatus() == castOther.getLoginStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + this.getLoginStatus();
		return result;
	}

}

