package com.v2soft.training.dataModel;

import java.util.HashSet;
import java.util.Set;


/**
 * Login generated by hbm2java
 */

public class LoginInfo implements java.io.Serializable {

	private String userName;
	private EmployeeInfo employeeinfo;
	private String password;
	private Set<LoginSessionInfo> loginSessions = new HashSet<LoginSessionInfo>(0);

	public LoginInfo() {
	}

	public LoginInfo(String userName, EmployeeInfo employeeinfo, String password) {
		this.userName = userName;
		this.employeeinfo = employeeinfo;
		this.password = password;
	}

	public LoginInfo(String userName, EmployeeInfo employeeinfo, String password, Set<LoginSessionInfo> loginSessions) {
		this.userName = userName;
		this.employeeinfo = employeeinfo;
		this.password = password;
		this.loginSessions = loginSessions;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	
	public EmployeeInfo getEmployeeinfo() {
		return this.employeeinfo;
	}

	public void setEmployeeinfo(EmployeeInfo employeeinfo) {
		this.employeeinfo = employeeinfo;
	}

	
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	
	public Set<LoginSessionInfo> getLoginSessions() {
		return this.loginSessions;
	}

	public void setLoginSessions(Set<LoginSessionInfo> loginSessions) {
		this.loginSessions = loginSessions;
	}

}

